#Cypress testing workflow 

name: Cypress Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push, specify branch later
  push

jobs:

  install:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          with: npm install
          
#      - name: Save build folder
#        uses: actions/upload-artifact@v2
#        with:
#          name: build
#          if-no-files-found: error
#          path: build
