#Cypress testing workflow

name: Cypress Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push, specify branch later
  push

jobs:
  install-front:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Start postgress
          run: |
            sudo systemctl start postgresql.service
            sudo -u postgres createdb tourit_db
        - name: Node10
          uses: actions/setup-node@v2
          with:
            node-version: '10'
        - run: cd frontend/
        - run: npm i @vue/cli-service
        - run: npm install
        - run: npm run serve & wait-on http://localhost:8080