#Cypress testing workflow

name: Cypress Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push, specify branch later
  push

jobs:
  install-front:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
#        - name: Start postgress
#          run: |
#            sudo systemctl start postgresql.service
#            sudo -u postgres createdb tourit_db
#        - name: Python 3.7 install
#          uses: actions/setup-python@v2
#          with:
#            python-version: '3.7'
#        - name: Dependencies install and mod
#          run: |
#            pip3.7 install -r requirements.txt
#            sed 's/from werkzeug import cached_property/from werkzeug.utils import cached_property/' /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flask_restplus/fields.py
#            sed 's/from werkzeug import cached_property/from werkzeug.utils import cached_property/' /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flask_restplus/api.py
        - name: Node10
          uses: actions/setup-node@v2
          with:
            node-version: '10'
        - name: install deps
          run: |
            npm install
            npm install -g lambdatest-cypress-cli
            pwd
        - name: Lambda-cypress run
          run: lambdatest-cypress run